apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: exposecontroller
    fabric8.io/git-commit: b4c8732eca2d825bb38f23b399924861ac7d7f75
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=exposecontroller&var-version=4.0.197
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/exposecontroller
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/exposecontroller
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-platform/master/apps/exposecontroller/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v4.0.197
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/exposecontroller
    fabric8.io/scm-tag: app-console-2.0.1
  labels:
    app: exposecontroller
    provider: fabric8
    version: 4.0.197
    group: io.fabric8.platform.apps
  name: exposecontroller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: exposecontroller
      provider: fabric8
      group: io.fabric8.platform.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: b4c8732eca2d825bb38f23b399924861ac7d7f75
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=exposecontroller&var-version=4.0.197
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/exposecontroller
        fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/exposecontroller
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-platform/master/apps/exposecontroller/src/main/fabric8/icon.png
        configmap.fabric8.io/update-on-change: exposecontroller
        fabric8.io/git-branch: release-v4.0.197
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/exposecontroller
        fabric8.io/scm-tag: app-console-2.0.1
      labels:
        app: exposecontroller
        provider: fabric8
        version: 4.0.197
        group: io.fabric8.platform.apps
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabric8/exposecontroller:2.3.28
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/restarteveryday
          initialDelaySeconds: 86164
        name: exposecontroller
        volumeMounts:
        - mountPath: /etc/exposecontroller
          name: config-volume
      serviceAccountName: int-exposecontroller
      volumes:
      - configMap:
          name: exposecontroller
        name: config-volume